### ISSUE TITLE
Enhancement - GitHub assets

### ISSUE THREAD

**Issue by super-sk** [johnthagen/python-blueprint#13]
For opensource project, you could add a minimal `.github` folder for _issues_ and _PRs_ .

```
.github/
├── ISSUE_TEMPLATE.md
└── PULL_REQUEST_TEMPLATE.md
```

Anyway, your `python-blueprint` is awesome. Good job ! ;)

**Comment by johnthagen** [comment]
> Anyway, your python-blueprint is awesome. Good job ! ;)

Thanks!

> For opensource project, you could add a minimal .github folder for issues and PRs .

Given this project is just a template/example, I'm not sure exactly what I'd put in there. I'd expect most issues or pull requests to be pretty straight forward and not require too much boilerplate.
