### ISSUE TITLE
Poetry integration

### ISSUE THREAD

**Issue by johnthagen** [johnthagen/python-blueprint#16]
[Poetry](https://python-poetry.org/) recently went 1.0, and looks pretty good. It's inspired by really solid package managers like [Cargo](https://doc.rust-lang.org/cargo/).

There are some [`tox` related issues](https://github.com/python-poetry/poetry/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+tox) that looked a bit concerning.

Should continue to monitor it, and if it continues to gain market share and maturity, consider switching from recommending `pip-tools` to `poetry`.

Related to #7

**Comment by johnthagen** [comment]
These kinds of issues give me pause: https://github.com/python-poetry/poetry/issues/760

Probably safer to wait until `poetry` has matured before recommending its blanket use.

**Comment by johnthagen** [comment]
PyCharm support for poetry feature request: https://youtrack.jetbrains.com/issue/PY-30702

**Comment by johnthagen** [comment]
https://plugins.jetbrains.com/plugin/14307-poetry

**Comment by johnthagen** [comment]
After trying this out, there still seem to be multiple rough edges integrating `poetry` with `tox` and wanting to not duplicate dev-dependencies, mostly summed up in this issue: https://github.com/python-poetry/poetry/issues/1745

A minimal set up looks like:

```ini
[tox]
isolated_build = true
requires =
    tox-poetry-dev-dependencies>=0.0.5

[testenv:lint]
# Using the lock file can produce an install errors due to missing markers support.
# poetry_experimental_add_locked_dependencies = True
poetry_add_dev_dependencies = True
commands =
    flake8
```

```toml
# pyproject.toml
[tool.poetry.dev-dependencies]
flake8 = "^3.8.4"
```

There are several outstanding issues with this:

- Lockfiles can't be used reliably, so `tox` won't be using the dependencies unless they are pinned exactly in `pyproject.toml` (which defeats the ease of use of `poetry update) due to: https://github.com/sinoroc/tox-poetry-dev-dependencies/issues/48
- The PyCharm tox run configuration fails to launch in this way:

```
Testing started at 11:51 AM ...
/Users/hagenjt1/Library/Caches/pypoetry/virtualenvs/bellwether-08XtBG_X-py3.8/bin/python /Applications/PyCharm.app/Contents/plugins/python/helpers/pycharm/_jb_tox_runner.py "-e fmt-check"
Traceback (most recent call last):
  File "/Applications/PyCharm.app/Contents/plugins/python/helpers/pycharm/_jb_tox_runner.py", line 132, in <module>
    config = tox_config.parseconfig(args=sys.argv[1:])
  File "venv/lib/python3.8/site-packages/tox/config/__init__.py", line 278, in parseconfig
    ParseIni(config, config_file, content)
  File "venv/lib/python3.8/site-packages/tox/config/__init__.py", line 1201, in __init__
    self.handle_provision(config, reader)
  File "venv/lib/python3.8/site-packages/tox/config/__init__.py", line 1289, in handle_provision
    raise tox.exception.MissingRequirement(config)
tox.exception.MissingRequirement: <exception str() failed>

Process finished with exit code 1

Empty suite
```

**Comment by johnthagen** [comment]
A slightly better solution that I've tried so far. This will actually use the `poetry.lock` file.

```ini
[tox]
envlist =
    fmt-check
    lint
skip_missing_interpreters = true
skipsdist = true
isolated_build = true

[flake8]
max-line-length = 99
extend-ignore = E203

[testenv]
# Tox environments automatically inherit settings from the main testenv.
require_locked_deps = true

[testenv:lint]
deps =
    flake8
commands =
    flake8

[testenv:fmt]
deps =
    isort
    black
commands =
    isort .
    black .

[testenv:fmt-check]
deps =
    isort
    black
commands =
    isort --check-only .
    black --check .
```

```toml
[tool.poetry.dev-dependencies]
tox = "^3.20.1"
tox-poetry-installer = "^0.2.4"
```

**Comment by johnthagen** [comment]
The latest `tox` configuration I have been trying with Poetry using [`tox-poetry-installer`](https://github.com/enpaul/tox-poetry-installer/):

```ini
[tox]
envlist =
    fmt-check
    lint
    docs
    py{38,39}
skipsdist = true
skip_missing_interpreters = true
isolated_build = true
requires =
    tox-poetry-installer[poetry] == 0.8.1

[testenv]
require_locked_deps = true
install_project_deps = true
install_dev_deps = true
commands =
    {envpython} -m pytest --cov=fact --cov-report=html --cov-report=term {posargs}

[testenv:type-check]
install_project_deps = false
# Require all dev_deps to install types-* packages.
install_dev_deps = true
commands =
    mypy src tests

[testenv:lint]
install_project_deps = false
install_dev_deps = false
locked_deps =
    flake8
    pep8-naming
commands =
    flake8

[testenv:fmt]
install_project_deps = false
install_dev_deps = false
locked_deps =
    isort
    black
commands =
    isort .
    black .

[testenv:fmt-check]
install_project_deps = false
install_dev_deps = false
locked_deps =
    isort
    black
commands =
    isort --check-only .
    black --check .
```

**Comment by InCogNiTo124** [comment]
I'd like to chime in and say that poetry integration would be marvellous

**Comment by johnthagen** [comment]
The [`export`](https://python-poetry.org/docs/cli#export) command can be used to work around the Poetry bootstrapping issue where a project is moved into a network where Poetry is challenging to install (but `pip` is bundled with Python).

**Comment by johnthagen** [comment]
Poetry 1.2 dependency groups look very promising. After 1.2 is released and the dust settles, investigate Poetry and PyCharm support for 1.2.

- https://python-poetry.org/blog/announcing-poetry-1.2.0a2/#dependency-groups
