### ISSUE TITLE
Migrate flake8 config to pyproject.toml

### ISSUE THREAD

**Issue by johnthagen** [johnthagen/python-blueprint#29]
If/when the `flake8` developers decide to support `pyproject.toml`, should move `flake8` configuration to that to consolidate configurations.

- https://github.com/PyCQA/flake8/issues/234 (locked)

# Current Status

This comment lists blockers the Flake8 developers have listed:

- https://github.com/PyCQA/flake8/issues/234#issuecomment-812800722

- [ ] "pip to change its behaviour so mere presence of the file does not change functionality"
  - https://github.com/pypa/pip/issues/9175
  - https://github.com/pypa/pip/issues/8102
- [x] "neither toml nor the python implementations are even 1.0"
  - [The TOML language is 1.0](https://toml.io/en/v1.0.0)
- [x] "python to consider adding a standard library toml implementation"
  - [`tomllib` has been added to Python 3.11](https://docs.python.org/3.11/library/tomllib.html#module-tomllib)

This comment lists a non-technical reason a Flake8 developer has against TOML (against the creator of TOML himself):

- https://github.com/PyCQA/flake8/issues/1467#issuecomment-1044442694

Recent tweets:

- https://twitter.com/codewithanthony/status/1556976653208780805
  - Using TOML has the risk of breaking Flake8 plugins
- https://twitter.com/codewithanthony/status/1556979272534876160?s=20&t=ZnRLnfD4K4JIXmyqQq5zxg
  - Due to the complexity of Flake8's configuration system, adding TOML support would require a full rewrite of the plugin system

**Comment by drhagen** [comment]
Issue for `flake8` `pyproject.toml` support was [migrated](https://github.com/PyCQA/flake8/issues/234) and locked.

**Comment by Halkcyon** [comment]
@drhagen reading through that with the broken links is quite a mess.  Has any progress been made in the year+ since that issue was closed on supporting `pyproject.toml` like a lot of other popular packages have?

**Comment by agronholm** [comment]
As a workaround, you can use [pyproject-flake8](https://pypi.org/project/pyproject-flake8/).

**Comment by johnthagen** [comment]
[bpo-40059](https://bugs.python.org/issue40059) is tracking the discussion about adding TOML parsing to the stdlib, which has historically been one of the blockers that the `flake8` maintainer has listed as a reason to supporting `pyproject.toml`.

Also see:

- https://github.com/hukkin/tomli/issues/141

**Comment by johnthagen** [comment]
`tomli` has been accepted into the stdlib for 3.11+

- https://github.com/hukkin/tomli/issues/141#issuecomment-1047797677

**Comment by johnthagen** [comment]
[`pyproject-flake8`](https://github.com/csachs/pyproject-flake8) does not seem very well maintained (last commit 1 year ago).

**Comment by agronholm** [comment]
It's a crutch until flake8 itself gets TOML support. Now that TOML support is in stdlib, there shouldn't be any excuse left for them not to add pyproject.toml support.

**Comment by johnthagen** [comment]
It appears that the recent acceptance of `tomllib` into the std library has not been enough to motivate `flake8` to begin adding support at this time:

- https://github.com/PyCQA/flake8/issues/1570
- https://github.com/PyCQA/flake8/issues/1571

**Comment by agronholm** [comment]
This looks like a people problem, rather than a technical problem.

**Comment by johnthagen** [comment]
#91 uses [`pyproject-flake8`](https://github.com/csachs/pyproject-flake8) to move `flake8` configuration into `pyproject.toml`. I am going to leave this issue open until `flake8` adds native support for `pyproject.toml`, as there are certain edge cases that (e.g. editors shelling out to `flake8`) that this does not fully solve.

**Comment by flying-sheep** [comment]
The only problem with `pyproject-flake8` is that its versions don’t reflect flake8 versions, so `pre-commit autoupdate` doesn’t bump its version which means the cache will continue to hold the `flake8` version that was downloaded when the newest `pyproject-flake8` was released.

**Comment by agronholm** [comment]
Which is why it would be nice to get that support in upstream flake8 now that all of the blockers should be gone.

**Comment by johnthagen** [comment]
Summary of recent closed requests:

- https://github.com/PyCQA/flake8/issues/1598
- https://github.com/PyCQA/flake8/issues/1632
- https://github.com/PyCQA/flake8/issues/1651
- https://github.com/PyCQA/flake8/issues/1655

**Comment by agronholm** [comment]
It is clear now that this is not about technical issues, but Anthony's personal problems.

**Comment by flying-sheep** [comment]
I think there’s two facets to this:

1. The opaque approach the PyCQA people are taking here with closing & locking mostly* without even hinting at the reason. They don’t treat people with respect, they don’t acknowledge any of the arguments, they just cut off communication as if everyone was a bad faith actor or obviously wrong. I think that’s inexcusable. People write these issues because they want to make things better, not to spite Anthony or something.

   *The only hint I saw is https://github.com/PyCQA/flake8/issues/1632#issuecomment-1200525722 where Anthony says “neither of the pip issues you linked are related”.

3. One of the things Anthony considers a hard blocker still remains: Pip is still branching behavior based on the presence of `pyproject.toml`, specifically build isolation.

   @NeilGirdhar’s issue above does indeed link unrelated pip issues, as can be glanced from https://github.com/pypa/pip/issues/8437#issuecomment-805321274: Pip uses build isolation independently from PEP 517: `--no-use-pep517` doesn’t turn it off.

To fix the bad blood, the PyCQA people need to start respecting people filing issues and explicitly link the pip issues that point out that their blocker is still not resolved.

To fix the underlying technical issue, pip would need to switch build isolation on or off based on a criterion other than `Path('pyproject.toml').is_file()`. Unconditionally on would work for the flake8 maintainers (as stated in an email) or switching based on the `[build-system]` table (I assume).

**Comment by agronholm** [comment]
Hm, I was under the impression that nowadays pip only does an isolated build if the `build-system` section is found in `pyproject.toml`. Am I mistaken?

**Comment by flying-sheep** [comment]
You are! I checked the current `main` branch code: 

1. The `build_isolation` config value is `True` by default and means “are we allowed to use build isolation?” (can be turned off via `--no-build-isolation`)
2. A requirement’s `use_pep517` defaults to [`has_pyproject or not importlib.util.find_spec("setuptools")`](https://github.com/pypa/pip/blob/main/src/pip/_internal/pyproject.py#L91-L101) (can be specified via `--use-pep517`/`--no-use-pep517`)
3. pip will use build isolation [`if self.req.use_pep517 and build_isolation`](https://github.com/pypa/pip/blob/e2c9c40edeb65b9d26c13a12dbe5642dc2e00fd0/src/pip/_internal/distributions/sdist.py#L34)

Therefore without specifying any of the mentioned CLI options and with setuptools installed, build isolation depends on the existence of `pyproject.toml`, not its contents.

**Comment by agronholm** [comment]
Then it was at least discussed somewhere. Would seem like a good change to make in pip, yes?

**Comment by flying-sheep** [comment]
The discussions I found are a bit older, so it makes sense to e.g. ask @pfmoore if this quote (from the comment linked above) still applies:

> I'd argue for "no PEP 517 if there's no build-system" but with the explicit clarification that this does not disable build isolation, it simply does what --no-use-pep517 does.

After all, pip’s maintainers *do* accept arguments that were posed in good faith.

**Comment by NeilGirdhar** [comment]
@flying-sheep 

> The only hint I saw was in @NeilGirdhar’s issue https://github.com/PyCQA/flake8/issues/1632#issuecomment-1200525722 where Anthony says “neither of the pip issues you linked are related”.

FYI They not only closed my issue, but Ian Cordasco immediately blocked me from PyCQA (flake8, pylint, etc.) for posting that issue.  I asked Ian for clarification, but he ignored my emails for the last few weeks.  Also, Anthony was extremely disrespectful in the email exchange I had with him.  These are not  people that I want to interact with anymore.

**Comment by johnthagen** [comment]
Hey all, happy to use this as a forum to track status and discuss technical productive ways to improve the situation, but please refrain from personal attacks of any kind.

**Comment by johnthagen** [comment]
I am considering trying out this Flake8 workaround instead:

- https://github.com/john-hen/Flake8-pyproject
- https://github.com/john-hen/Flake8-pyproject/issues/2

The main advantages being:

- It still allows the user to run `flake8` rather than `pflake8`. This helps with some editor integration.
- It doesn't monkey patch, so it _might_ be a more stable way to get this functionality than `pyproject-flake8`

Disadvantages:

- It is more complex than `pyproject-flake8`

**Comment by flying-sheep** [comment]
I just came across https://github.com/charliermarsh/ruff, which seems like a great and fast alternative to flake8, isort, …

**Comment by johnthagen** [comment]
> I just came across https://github.com/charliermarsh/ruff,

Yes, I've been keeping my eye on Ruff as well. It looks very promising.

**Comment by johnthagen** [comment]
I have decided to migrate from `Flake8` to [`Ruff`](https://beta.ruff.rs/docs/) for a variety of reasons. Ruff natively supports `pyproject.toml` so this particular papercut is solved with it.

To look at how I choose to do the migration, see 

- #164
