### ISSUE TITLE
pytest and top-level source packages have a bad interaction

### ISSUE THREAD

**Issue by drhagen** [johnthagen/python-blueprint#4]
The blueprint uses pytest with a `tests` folder that is a true Python package (it contains a `__init__.py` file). [This is known](https://docs.pytest.org/en/latest/goodpractices.html#tests-outside-application-code) to interact badly with having packages defined at the top level—in this case, `fact`. This is especially problematic when using tox, which the blueprint also uses. tox installs the distribution in a virtual environment so that the distribution itself can be tested. However, pytest adds to `sys.path` all directories containing test packages. Because `tests` is a package, the project root is added to `sys.path` and the `fact` package in the project root _shadows_ the `fact` package installed in the tox environment. Then that means that the `fact` package being tested is actually the source package and not the `fact` package installed. pytest and tox may report a success even if there are problems with the packaging of the distribution.

There are a few possible solutions to ensuring that the project root does not end up included in `sys.path`:

- Remove the `__init__.py` file from `tests`, which prevents `pytest` from adding the project root to `sys.path` and run `pytest` directly as a tox command, not via `python -m pytest` [to prevent `python` from adding the project root to `sys.path`](https://docs.pytest.org/en/latest/pythonpath.html#invoking-pytest-versus-python-m-pytest).
- Remove the `__init__.py` file from `tests` and change the working directory of the test command to `tests`.
- Move the source package to a `src` folder. [This is the recommended solution](https://docs.pytest.org/en/latest/pythonpath.html#test-modules-conftest-py-files-inside-packages) by `pytest` when using tox.

**Comment by johnthagen** [comment]
This issue has lots of awesome links and explanation. Can some condensed form of this end up in the README? Maybe a short section on "Why to use `src`" or something.
